### ISSUE TITLE
lgtv-config 

### ISSUE THREAD

**Issue by Paul-Reed** [hobbyquaker/node-red-contrib-lgtv#1]
Hi, thanks for submitting!
Could you explain how to setup the lgtv-config please, I don't know where to find the 'host' & 'token' details.

Paul

**Comment by hobbyquaker** [comment]
Hi!
The Token isn't meant to be filled manually, this should be auto-filled on first connect to your TV. You just have to put in the Hostname or IP-Address of your LG TV. If DNS is working in your Network the default `lgwebostv` should be ok, otherwise you would have to find out the IP Address of the TV (possibly you can look it up in your routers web ui) and use this. Then just press the connect button (your TV needs to be switched on for at least ~25s when doing this) and as soon as the Token field got filled you're ready to go.
Don't hesitate to ask if you still experience problems,
Regards,
Sebastian

**Comment by hobbyquaker** [comment]
added setup instructions to the readme
